/**
 * Markdown 渲染器 (Phase 8)
 *
 * 把 SQLite 数据渲染成稳定的 Markdown 字符串。
 * - 不调用文件系统
 * - 不调用数据库
 * - 不泄露 API Key / Provider 配置
 * - 纯函数（输入数据 → 输出 string）
 */

import { format } from "date-fns";
import type { JournalEntryRow, TaskRow, IdeaRow, ReviewRow } from "@/types/db";
import type { TaskStatusGroup } from "@/lib/repositories/task-repo";
import { parseSections, parseSourceEventIds } from "@/lib/repositories/review-repo";

/** 标记：烛照生成的文件 */
export const ZHUZHAO_GENERATED_MARKER =
  "<!-- Generated by Zhuzhao. Do not edit this file if you expect regeneration. -->";

/** 安全转义文件名中的非法字符 */
export function safeFilename(name: string): string {
  return name.replace(/[<>:"/\\|?*\x00-\x1f]/g, "_").trim();
}

/** 把 ISO 时间格式化为本地 YYYY-MM-DD HH:mm */
function fmtLocal(iso: string | null | undefined): string {
  if (!iso) return "—";
  try {
    const d = new Date(iso);
    if (isNaN(d.getTime())) return iso;
    return format(d, "yyyy-MM-dd HH:mm");
  } catch {
    return iso;
  }
}

/** 解析 JSON 字符串数组 */
function parseTags(tags: string | null | undefined): string[] {
  if (!tags) return [];
  try {
    const arr = JSON.parse(tags);
    if (Array.isArray(arr)) return arr.map(String);
  } catch {}
  return [];
}

/** 渲染 Daily Markdown */
export interface DailyRenderInput {
  date: string; // YYYY-MM-DD
  review: ReviewRow | null;
  journals: JournalEntryRow[];
  tasksDone: TaskRow[];
  tasksDelayed: TaskRow[];
  ideas: IdeaRow[];
}

export function renderDailyMarkdown(input: DailyRenderInput): string {
  const { date, review, journals, tasksDone, tasksDelayed, ideas } = input;
  const lines: string[] = [];

  lines.push(ZHUZHAO_GENERATED_MARKER);
  lines.push("");
  lines.push(`# ${date} 烛照每日回顾`);
  lines.push("");
  lines.push(`> 生成时间：${fmtLocal(new Date().toISOString())}`);
  lines.push("");

  // Daily Summary
  lines.push("## 今日总结");
  lines.push("");
  if (review) {
    const sections = parseSections(review.sections);
    lines.push("### 摘要");
    lines.push("");
    lines.push(review.raw_content);
    lines.push("");

    if (sections?.wins && sections.wins.length > 0) {
      lines.push("### 做成的");
      lines.push("");
      for (const w of sections.wins) lines.push(`- ${w}`);
      lines.push("");
    }
    if (sections?.delays && sections.delays.length > 0) {
      lines.push("### 拖延的");
      lines.push("");
      for (const d of sections.delays) lines.push(`- ${d}`);
      lines.push("");
    }
    if (sections?.topNext) {
      lines.push("### 明天最重要的一件事");
      lines.push("");
      lines.push(`**${sections.topNext}**`);
      lines.push("");
    }
    if (sections?.improvement) {
      lines.push("### 改进建议");
      lines.push("");
      lines.push(`> ${sections.improvement}`);
      lines.push("");
    }

    const srcIds = parseSourceEventIds(review.source_event_ids);
    if (srcIds.length > 0) {
      lines.push("### 来源 events");
      lines.push("");
      for (const id of srcIds) lines.push(`- ${id}`);
      lines.push("");
    }
  } else {
    lines.push("> 今日暂无生成总结。可在 Journal 或 Dashboard 页点击「生成今日总结」。");
    lines.push("");
  }

  // Journal Entries
  if (journals.length > 0) {
    lines.push("## 今日日记");
    lines.push("");
    for (const j of journals) {
      lines.push(`### ${fmtLocal(j.created_at)}`);
      lines.push("");
      lines.push("**原文：**");
      lines.push("");
      lines.push(j.raw_content);
      lines.push("");
      if (j.ai_summary) {
        lines.push(`**AI 摘要：** ${j.ai_summary}`);
        lines.push("");
      }
      const meta: string[] = [];
      if (j.mood) meta.push(`mood: ${j.mood}`);
      const tags = parseTags(j.tags);
      if (tags.length > 0) meta.push(`tags: ${tags.join(", ")}`);
      if (j.source_event_id) meta.push(`event: ${j.source_event_id}`);
      if (meta.length > 0) {
        lines.push(`> ${meta.join(" · ")}`);
        lines.push("");
      }
    }
  }

  // Tasks Done
  if (tasksDone.length > 0) {
    lines.push("## 今日完成");
    lines.push("");
    for (const t of tasksDone) {
      lines.push(`- [x] ${t.title}`);
      if (t.completed_at) {
        lines.push(`  - 完成于 ${fmtLocal(t.completed_at)}`);
      }
    }
    lines.push("");
  }

  // Tasks Delayed
  if (tasksDelayed.length > 0) {
    lines.push("## 今日延期");
    lines.push("");
    for (const t of tasksDelayed) {
      lines.push(`- [ ] ${t.title} (delay_count=${t.delay_count})`);
      if (t.due_at) lines.push(`  - due: ${fmtLocal(t.due_at)}`);
      if (t.failure_reason) lines.push(`  - 原因：${t.failure_reason}`);
    }
    lines.push("");
  }

  // Ideas
  if (ideas.length > 0) {
    lines.push("## 今日灵感");
    lines.push("");
    for (const i of ideas) {
      lines.push(`### ${i.title}`);
      lines.push("");
      lines.push(i.raw_content);
      lines.push("");
      const tags = parseTags(i.tags);
      if (tags.length > 0) {
        lines.push(`> tags: ${tags.join(", ")} · status: ${i.status}`);
      } else {
        lines.push(`> status: ${i.status}`);
      }
      lines.push("");
    }
  }

  return lines.join("\n");
}

/** 渲染 Journal Markdown（单个日期的日记合集） */
export function renderJournalMarkdown(
  date: string,
  journals: JournalEntryRow[],
): string {
  const lines: string[] = [];
  lines.push(ZHUZHAO_GENERATED_MARKER);
  lines.push("");
  lines.push(`# ${date} 日记`);
  lines.push("");
  lines.push(`> 生成时间：${fmtLocal(new Date().toISOString())}`);
  lines.push("");
  if (journals.length === 0) {
    lines.push("> 当日无日记。");
    lines.push("");
    return lines.join("\n");
  }
  for (const j of journals) {
    lines.push(`## ${fmtLocal(j.created_at)}`);
    lines.push("");
    lines.push("**原文：**");
    lines.push("");
    lines.push(j.raw_content);
    lines.push("");
    if (j.ai_summary) {
      lines.push(`**AI 摘要：** ${j.ai_summary}`);
      lines.push("");
    }
    const meta: string[] = [];
    if (j.mood) meta.push(`mood: ${j.mood}`);
    const tags = parseTags(j.tags);
    if (tags.length > 0) meta.push(`tags: ${tags.join(", ")}`);
    if (j.source_event_id) meta.push(`event: ${j.source_event_id}`);
    if (meta.length > 0) {
      lines.push(`> ${meta.join(" · ")}`);
      lines.push("");
    }
    lines.push("---");
    lines.push("");
  }
  return lines.join("\n");
}

/** 渲染 Tasks Markdown（全部任务，按状态分组） */
export interface TasksRenderInput {
  inbox: TaskRow[];
  active: TaskRow[];
  delayed: TaskRow[];
  done: TaskRow[];
  overdue: TaskRow[];
}

const STATUS_GROUP_LABEL: Record<TaskStatusGroup | "overdue", string> = {
  inbox: "Inbox",
  active: "进行中",
  delayed: "已延期",
  done: "已完成",
  archived: "已归档",
  overdue: "已逾期",
};

function renderTaskItem(t: TaskRow, includeDelay = false): string[] {
  const lines: string[] = [];
  const check = t.status === "done" ? "[x]" : "[ ]";
  lines.push(`- ${check} ${t.title}`);
  const meta: string[] = [];
  meta.push(`status: ${t.status}`);
  if (t.priority) meta.push(`priority: ${t.priority}`);
  if (t.due_at) meta.push(`due: ${fmtLocal(t.due_at)}`);
  if (t.completed_at) meta.push(`completed: ${fmtLocal(t.completed_at)}`);
  if (includeDelay) meta.push(`delay_count: ${t.delay_count}`);
  if (t.failure_reason) meta.push(`原因: ${t.failure_reason}`);
  lines.push(`  - ${meta.join(" · ")}`);
  return lines;
}

export function renderTasksMarkdown(input: TasksRenderInput): string {
  const lines: string[] = [];
  lines.push(ZHUZHAO_GENERATED_MARKER);
  lines.push("");
  lines.push("# 烛照任务清单");
  lines.push("");
  lines.push(`> 生成时间：${fmtLocal(new Date().toISOString())}`);
  lines.push("");

  // Overdue
  if (input.overdue.length > 0) {
    lines.push(`## ⚠ ${STATUS_GROUP_LABEL.overdue} (${input.overdue.length})`);
    lines.push("");
    for (const t of input.overdue) {
      lines.push(...renderTaskItem(t, true));
    }
    lines.push("");
  }

  // Inbox
  if (input.inbox.length > 0) {
    lines.push(`## ${STATUS_GROUP_LABEL.inbox} (${input.inbox.length})`);
    lines.push("");
    for (const t of input.inbox) {
      lines.push(...renderTaskItem(t, true));
    }
    lines.push("");
  }

  // Active
  if (input.active.length > 0) {
    lines.push(`## ${STATUS_GROUP_LABEL.active} (${input.active.length})`);
    lines.push("");
    for (const t of input.active) {
      lines.push(...renderTaskItem(t, true));
    }
    lines.push("");
  }

  // Delayed
  if (input.delayed.length > 0) {
    lines.push(`## ${STATUS_GROUP_LABEL.delayed} (${input.delayed.length})`);
    lines.push("");
    for (const t of input.delayed) {
      lines.push(...renderTaskItem(t, true));
    }
    lines.push("");
  }

  // Done
  if (input.done.length > 0) {
    lines.push(`## ${STATUS_GROUP_LABEL.done} (${input.done.length})`);
    lines.push("");
    for (const t of input.done) {
      lines.push(...renderTaskItem(t, false));
    }
    lines.push("");
  }

  return lines.join("\n");
}

/** 渲染 Ideas Markdown */
export function renderIdeasMarkdown(ideas: IdeaRow[]): string {
  const lines: string[] = [];
  lines.push(ZHUZHAO_GENERATED_MARKER);
  lines.push("");
  lines.push("# 烛照灵感清单");
  lines.push("");
  lines.push(`> 生成时间：${fmtLocal(new Date().toISOString())}`);
  lines.push("");
  if (ideas.length === 0) {
    lines.push("> 暂无灵感。");
    lines.push("");
    return lines.join("\n");
  }
  for (const idea of ideas) {
    lines.push(`## ${idea.title}`);
    lines.push("");
    lines.push(idea.raw_content);
    lines.push("");
    const meta: string[] = [];
    if (idea.status) meta.push(`status: ${idea.status}`);
    const tags = parseTags(idea.tags);
    if (tags.length > 0) meta.push(`tags: ${tags.join(", ")}`);
    if (idea.source_event_id) meta.push(`event: ${idea.source_event_id}`);
    meta.push(`created: ${fmtLocal(idea.created_at)}`);
    lines.push(`> ${meta.join(" · ")}`);
    lines.push("");
    lines.push("---");
    lines.push("");
  }
  return lines.join("\n");
}

/** 渲染 Index Markdown */
export function renderIndexMarkdown(dates: string[]): string {
  const lines: string[] = [];
  lines.push(ZHUZHAO_GENERATED_MARKER);
  lines.push("");
  lines.push("# 烛照导出索引");
  lines.push("");
  lines.push(`> 生成时间：${fmtLocal(new Date().toISOString())}`);
  lines.push("");
  lines.push("## 目录结构");
  lines.push("");
  lines.push("- `Daily/YYYY-MM-DD.md` — 每日回顾（含总结、日记、任务、灵感）");
  lines.push("- `Journal/YYYY-MM-DD.md` — 当日日记原文合集");
  lines.push("- `Tasks/tasks.md` — 全部任务清单（按状态分组）");
  lines.push("- `Ideas/ideas.md` — 全部灵感清单");
  lines.push("");
  if (dates.length > 0) {
    lines.push("## 已导出的 Daily");
    lines.push("");
    for (const d of dates) {
      lines.push(`- [[Daily/${d}|${d}]]`);
    }
    lines.push("");
  }
  lines.push("## 说明");
  lines.push("");
  lines.push("- 本目录下所有 `.md` 文件由烛照生成，可重新生成覆盖。");
  lines.push("- 文件顶部带 `Generated by Zhuzhao` 标记的，可被烛照覆盖。");
  lines.push("- 没有该标记的用户文件不会被覆盖。");
  lines.push("- SQLite 仍是唯一主数据源，Markdown 仅作为导出视图。");
  lines.push("");
  return lines.join("\n");
}
